spring:
  redis:
    host: 129.211.48.120
    port: 6379
    database: 0
  application:
    name: auth-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9001
